### ISSUE TITLE
Px4 SLAM odometry 

### ISSUE THREAD

**Issue by giangdao1402** [engcang/SLAM-application#12]
Hi @engcang 
Thank for your great repo !
I saw a lot of your videos on YTB with LIDAR-SLAM.
I just want to ask how can you use LIDAR-SLAM to fly with PX4 without GPS.
Thank you !!!

**Comment by engcang** [comment]
Hi @giangdao1402 You can refer to this documentation - https://docs.px4.io/main/en/ros/external_position_estimation.html

**Comment by giangdao1402** [comment]
Thank you !
