### ISSUE TITLE
What is the paper of ADA-LIO？

### ISSUE THREAD

**Issue by Gatsby23** [engcang/SLAM-application#7]

**Comment by engcang** [comment]
Hi @Gatsby23. The paper can be found here - https://www.researchgate.net/publication/370262793_AdaLIO_Robust_Adaptive_LiDAR-Inertial_Odometry_in_Degenerate_Indoor_Environments

**Comment by hunkyu** [comment]
ADA-LIO IS OPEN SOURCE?

**Comment by engcang** [comment]
@hunkyu ADA-LIO is closed-source method. If you want to test it with your own dataset, you may send the wanted dataset to me.
