### ISSUE TITLE
ImMesh

### ISSUE THREAD

**Issue by satyajitghana** [engcang/SLAM-application#9]
ImMesh was released! time to try it out: https://github.com/hku-mars/ImMesh

**Comment by engcang** [comment]
@satyajitghana Wow. Thank you for letting me know! 
Let me try tonight or tomorrow night :)

**Comment by satyajitghana** [comment]
I had some mixed results, it sort of works really well if there's no drift. If there is, then the mesh looks really bad. Want to see how it works out for your dataset.
